# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: none
#relative_permalinks: true #stringa originale
relative_permalinks: false

# Setup
title: limulo
tagline: 'sound design and coding'
description: 'sound design and coding'
url: http://www.limulo.net
baseurl: /website
#baseurl: /site/

author:
  name: limulo.net
  url: https://twitter.com/Limulo_lab

#paginate: 5

comments: true

gems:
  - jekyll-paginate

# Custom vars
version:
github:
  repo: https://github.com/Limulo/website-restyle2016
thumbnail:
